{% set name = "scorecardpy" %}
{% set version = "0.1.9.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scorecardpy-{{ version }}.tar.gz
  sha256: a81c7e6f3bf5f10a87b61af73b25f1fc8bc5acbadf5d9e38c3addb02df128d03

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - numpy
    - pandas >=1.0.0
    - patsy
    - python >=3.6  
    - scikit-learn >=0.19.1
    - statsmodels

test:
  imports:
    - scorecardpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/shichenxie/scorecardpy
  summary: Credit Risk Scorecard
  dev_url: https://github.com/shichenxie/scorecardpy/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pn-alex
